routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return redirect('/admin/paciente');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->prefix('admin')->namespace('Admin')->group(function () {
    Route::resource('paciente', 'PacienteController');
    Route::get('lista-paciente/{status}', 'PacienteController@listFilter');
});

app/Paciente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

class Paciente extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $fillable = [
        'cpf', 'nome', 'rg', 'cartao_sus', 'sexo', 'nascimento', 'nome_mae', 'telefone', 'cep', 'avenida_rua',
        'numero', 'quadra', 'lote', 'complemento', 'bairro', 'cidade', 'uf', 'excluido'
    ];

    public static function listaPacientes($paginate, $status)
    {
        if (!$status) {
            $operator = '<>';
        } else {
            $operator = '=';
        }

        $listaPacientes = DB::table('pacientes')
            ->select('pacientes.id', 'pacientes.nome', 'pacientes.nascimento', 'pacientes.cpf')
            ->where('excluido', $operator, '1')
            ->orderBy('pacientes.id', 'DESC')
            ->paginate($paginate);

        return $listaPacientes;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/PacienteController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Paciente;
use Illuminate\Support\Facades\DB;

class PacienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function listFilter($status)
    {
        $listaPacientes = Paciente::listaPacientes(2, $status);

        //Calcula a idade
        foreach ($listaPacientes as $paciente => $value) {
            if (!empty($value->nascimento)) {
                list($ano, $mes, $dia) = explode('-', $value->nascimento);
                $hoje = mktime(0, 0, 0, date('m'), date('d'), date('Y'));
                $nascimento = mktime(0, 0, 0, $mes, $dia, $ano);
                $idade =  floor((((($hoje - $nascimento) / 60) / 60) / 24) / 365.25);
                if ($idade == 0.0) {
                    $value->nascimento = '0';
                } else {
                    $value->nascimento = $idade;
                }
            }
        }
        return view('admin.paciente.index', compact('listaPacientes', 'status'));
    }

    public function index()
    {
        $listaPacientes = Paciente::listaPacientes(2, null);
        $status = 0;

        //Calcula a idade
        foreach ($listaPacientes as $paciente => $value) {
            if (!empty($value->nascimento)) {
                list($ano, $mes, $dia) = explode('-', $value->nascimento);
                $hoje = mktime(0, 0, 0, date('m'), date('d'), date('Y'));
                $nascimento = mktime(0, 0, 0, $mes, $dia, $ano);
                $idade =  floor((((($hoje - $nascimento) / 60) / 60) / 24) / 365.25);
                if ($idade == 0.0) {
                    $value->nascimento = '0';
                } else {
                    $value->nascimento = $idade;
                }
            }
        }

        return view('admin.paciente.index', compact('listaPacientes', 'status'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        if ($data['id']) {
            //Atualizar
            $data = $request->all();
            Paciente::find($data['id'])->update($data);
            return redirect()->back();
        } else {
            //Cadastrar
            $data['excluido'] = 0;
            Paciente::create($data);
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $paciente = Paciente::find($id);
        return $paciente;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            DB::beginTransaction();
            $update = DB::table('pacientes')
                ->where('id', $id)
                ->update(['excluido' => 1]);

            if ($update) {
                DB::commit();
                $notification = array(
                    'message' => 'Paciente excluído com sucesso!',
                    'alert' => 'success'
                );
                return redirect()->back();
            } else {
                DB::rollBack();
                $notification = array(
                    'message' => 'Falha ao excluir paciente!',
                    'alert' => 'error'
                );
                return redirect()->back();
            }
        } catch (\Illuminate\Database\QueryException $e) {
            $erro = $e->errorInfo;
            if ($erro[1] == 1451) {
                $notification = array(
                    'message' => 'Registro não pode ser excluído pois está vinculado a outro registro!',
                    'alert' => 'error'
                );
                return redirect()->back();
                return response()->json($notification);
            }
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/admin/paciente/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <painel titulo="Pacientes">
                <formulario id="formAdicionar" id="$store.state.item.id" css="" action="{{route('paciente.store')}}" method="post" enctype="" token="{{ csrf_token() }}">
                    <div style="display: flex;">
                        <div style="padding-left: 0px;" class="col-md-2">
                            <div class="card" style="width: 10rem;">
                                <center>
                                    <div @drop="onImage(2, $event)" :class="dragEnter ? ['ondrag-enter'] : images[2].content ? ['drop']:['drop', 'ondrag-leave']" @dragover.prevent @dragenter="dragEnter = true" @dragleave="dragEnter = false">
                                        <h4 v-show="!images[2].content">Solte a sua foto aqui</h4>
                                        <img :src="images[2].content" width="120px" ref="resize" />
                                    </div>
                                </center>
                                <div style="text-align: center; padding: 10px;">
                                    <div class="upload-btn-wrapper">
                                        <button class="btn btn-success">
                                            Selecione
                                        </button>
                                        <input type="file" @change="onImage(2, $event)" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-10">
                            <input type="text" style="display: none;" value="$store.state.item.id" class="form-control" style="display:block;" id="id" name="id" v-model="$store.state.item.id">
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <input type="text" class="form-control" required id="cpf" name="cpf" v-model="$store.state.item.cpf" placeholder="CPF">
                                </div>
                                <div class="col-md-4">
                                    <input type="text" class="form-control" required id="nome" name="nome" v-model="$store.state.item.nome" placeholder="Nome do Paciente">
                                </div>
                                <div class="col-md-2">
                                    <input type="text" class="form-control" required id="rg" name="rg" v-model="$store.state.item.rg" placeholder="RG">
                                </div>
                                <div class="col-md-3">
                                    <input type="text" class="form-control" required id="cartao_sus" name="cartao_sus" v-model="$store.state.item.cartao_sus" placeholder="Cartão SUS">
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-2">
                                    <select id="sexo" class="form-control" v-model="$store.state.item.sexo" required name="sexo">
                                        <option selected="selected" value=" " disabled>Selecione o sexo</option>
                                        <option value="1">Feminino</option>
                                        <option value="2">Masculino</option>
                                    </select>
                                </div>
                                <div class="col-md-3">
                                    <input type="date" class="form-control" required id="nascimento" name="nascimento" v-model="$store.state.item.nascimento" placeholder="Nascimento">
                                </div>
                                <div class="col-md-4">
                                    <input type="text" class="form-control" required id="nome_mae" name="nome_mae" v-model="$store.state.item.nome_mae" placeholder="Nome da Mãe">
                                </div>
                                <div class="col-md-3">
                                    <input type="text" class="form-control" required id="telefone" name="telefone" v-model="$store.state.item.telefone" placeholder="Telefone">
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-2">
                                    <input type="text" class="form-control" required id="cep" name="cep" v-model="$store.state.item.cep" placeholder="CEP">
                                </div>
                                <div class="col-md-4">
                                    <input type="text" class="form-control" required id="avenida_rua" name="avenida_rua" v-model="$store.state.item.avenida_rua" placeholder="Avenida/Rua">
                                </div>
                                <div class="col-md-2">
                                    <input type="text" class="form-control" required id="numero" name="numero" v-model="$store.state.item.numero" placeholder="Número">
                                </div>
                                <div class="col-md-2">
                                    <input type="text" class="form-control" required id="quadra" name="quadra" v-model="$store.state.item.quadra" placeholder="Quadra">
                                </div>
                                <div class="col-md-2">
                                    <input type="text" class="form-control" required id="lote" name="lote" v-model="$store.state.item.lote" placeholder="Lote">
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <input type="text" class="form-control" required id="complemento" name="complemento" v-model="$store.state.item.complemento" placeholder="Complemento">
                                </div>
                                <div class="col-md-3">
                                    <input type="text" class="form-control" required id="bairro" name="bairro" v-model="$store.state.item.bairro" placeholder="Bairro">
                                </div>
                                <div class="col-md-3">
                                    <input type="text" class="form-control" required id="cidade" name="cidade" v-model="$store.state.item.cidade" placeholder="Cidade">
                                </div>
                                <div class="col-md-3">
                                    <input type="text" class="form-control" required id="uf" name="uf" v-model="$store.state.item.uf" placeholder="UF">
                                </div>
                            </div>
                            <div style="text-align: right;">
                                <button style="margin-bottom: 1%;" id="alt" form="formAdicionar" class="btn btn-info">Atualizar</button>
                                <button style="margin-bottom: 1%;" id="cad" form="formAdicionar" class="btn btn-info">Salvar</button>
                            </div>
                        </div>
                    </div>
                </formulario>
                <ul class="nav nav-tabs">
                    <form style="cursor: pointer;" class="form" id="form1" method="get" action="/admin/lista-paciente/{{0}}" enctype="multipart/form-data">
                        <li class="nav-item">
                            <a class="nav-link {{ $status ==  0 || !$status ? 'active' : ''  }}" onclick=" document.getElementById('form1').submit()">
                                Cadastros Ativos
                            </a>
                        </li>
                    </form>
                    <form style="cursor: pointer;" class="form" method="get" id="form2" action="/admin/lista-paciente/{{1}}" enctype="multipart/form-data">
                        <li class="nav-item">
                            <a class="nav-link {{ $status ==  1 ? 'active' : ''  }}" onclick="document.getElementById('form2').submit()">
                                Cadastros Excluídos
                            </a>
                        </li>
                    </form>
                </ul>
                <lista v-bind:titulos="['#','Nome','Idade','CPF']" v-bind:itens="{{json_encode($listaPacientes)}}" ordem="desc" ordemcol="0" criar="#criar" detalhe="/admin/paciente/" editar="/admin/paciente/" deletar="/admin/paciente/" token="{{ csrf_token() }}" modal="sim"></lista>
                <div style="float: right;">
                    {{$listaPacientes}}
                </div>
            </painel>
        </div>
    </div>
</div>

<script type="application/javascript" src="{{ asset('js/jquery.mask.min.js') }}"></script>

<script type="application/javascript">
    $(document).ready(function() {
        jQuery(function($) {
            if ($("#id").val() == '') {
                $("#cad").prop('disabled', false);
                $("#alt").prop('disabled', true);
            } else {
                $("#alt").prop('disabled', false);
                $("#cad").prop('disabled', true);
            }

            $("#cpf").mask("000.000.000-00");
            $("#telefone").mask("(00) 0 0000-0000");
            $("#cep").mask("00000-000");
        });
    })
</script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <!-- <div class="card">
                <div class="card-header">Dashboard</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    You are logged in!
                </div>
            </div> -->
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'EVTEK') }}</title>

    <!-- Scripts -->
    <script src="{!! asset('js/jquery-3.3.1.js') !!}" type="text/javascript"></script>
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
    <div id="app">
        <topo titulo="{{ config('app.name', 'Laravel') }}" url="{{ url('/') }}">
            <!-- <nav class="navbar navbar-expand-md navbar-light evtek-background shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'EVTEK') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <ul class="navbar-nav ml-auto">-->
            @guest
            <li class="nav-item">
                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
            </li>
            @if (Route::has('register'))
            <li class="nav-item">
                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
            </li>
            @endif
            @else
            <li class="nav-item dropdown">
                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    {{ Auth::user()->name }} <span class="caret"></span>
                </a>

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>
            @endguest
            <!-- </ul>
                    </div>
                </div>
            </nav> -->
        </topo>
        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

</html>